// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupportFlow.Modules.SupportOrganization.Infrastructure;

#nullable disable

namespace SupportFlow.Modules.SupportOrganization.Infrastructure.Migrations
{
    [DbContext(typeof(SupportOrganizationDbContext))]
    partial class SupportOrganizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportFlow.Modules.SupportOrganization.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_is_default")
                        .HasFilter("is_default");

                    b.ToTable("teams", "organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199c6a0-0000-7000-8000-000000000001"),
                            IsDefault = true,
                            Name = "Default"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
