// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupportFlow.Modules.Identity.Infrastructure;

#nullable disable

namespace SupportFlow.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20261010110036_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportFlow.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("account_type");

                    b.Property<string>("ExternalIssuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_issuer");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("ExternalIssuer", "ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_external_issuer_external_subject");

                    b.ToTable("user_accounts", "identity");
                });
#pragma warning restore 612, 618
        }
    }
}
