<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\SupportFlow.BuildingBlocks\SupportFlow.BuildingBlocks.csproj" />
    <ProjectReference Include="..\SupportFlow.Modules.AIAssistance.Contracts\SupportFlow.Modules.AIAssistance.Contracts.csproj" />
  </ItemGroup>

</Project>
